---
driver:
  name: lxd_api

provisioner:
  name: ansible_playbook
  roles_path: roles
  # require_chef_for_busser: false
  # require_ruby_for_busser: true

platforms:
  - name: oreno-ubuntu-14.04
    driver_plugin: lxd_api
    driver_config:
      container_image: oreno-ubuntu-image
      container_name: kitchen-container
      username: kitchen
      #
      # Optional
      #
      # architecture: 2
      # profiles: ["default"]
      # ephemeral: false
      # limits_cpu: "1"
      # timeout: 30
      # force: true

suites:
  - name: default
    provisioner:
      playbook: default.yml
      hosts: default

verifier:
  name: shell
  command: rspec -c -f d -I serverspec serverspec/common_spec.rb
